.TH Karn
.SH NAME
Karn - A simple and easy to use security profile generator
.SH SYNOPSIS
karn [OPTIONS] <Name_Of_Profile.toml>
.SH DESCRIPTION
A command line tool for generating seccomp and apparmor profiles to pass to your container runtime of choice

.SH VERSION
Alpha - 0.1
.SH AUTHOR
Grant Seltzer, <grant@capsule8.com>

