[System-Calls]
Allow = [
    "close",
    "mmap",
    "mmap2",
    "munmap",
    "getdtablesize",
    "dup",
    "dup2",
    "dup3",
    "read",
    "write",
    "flock",
    "fcntl",
    "fcntl64",
    "ioctl"
]