[System-Calls]
Allow = [
    "creat",
    "open",
    "truncate64",
    "ftruncate64",
    "ftruncate",
    "truncate", 
    "fstat64",
    "stat64",
    "lstat",
    "stat",
    "newfstatat",
    "fstatfs64",
    "statfs",
    "fstat",
    "lstat64",
    "fstatfs",
    "statfs64",
    "fstatat64",
    "pipe",
    "pipe2",
    "faccessat",
    "access",
    "fchmodat",
    "fchmod",
    "chmod",
    "chown32",
    "chown",
    "lchown",
    "fchown32",
    "fchown",
    "fchownat",
    "lchown32",
    "readlinkat",
    "symlink",
    "linkat",
    "unlinkat",
    "symlinkat",
    "readlink",
    "unlink",
    "link",
    "umask",
    "renameat2",
    "renameat",
    "rename",
    "lseek",
    "_llseek",
    "mkdir",
    "mkdirat",
    "mknod",
    "mknodat",
    "rmdir",
    "getdents64",
    "getdents",
    "chdir",
    "fchdir",
    "syncfs",
    "fsync",
    "fdatasync",
    "sync_file_range",
    "sync",
    "sync_file_range2",
    "msync"
]